#' preprocess
#'
#' @description \code{preprocess} is a utility function which help to generate a
#' dataset based on the original dataset in accordance with the description xlsx
#' file.
#'
#' @param data_set The dataset
#' @param xlsx_file The excel file generated by \code{data_overview}
#' @param sheetName The name of the sheet in the excel file
#' @param max_levels The tolerate maximum number of levels for a categorical
#' variable
#' @param max_uniratio The tolerate maximum ratio of a single value in a var
#' @param max_na_ratio The tolerate maximum ratio of missing value in a var
#' @return data.frame the cleaned \code{data.frame}
#'
#' @import xlsx
#' @importFrom stringr str_to_lower
#' @export

preprocess <- function(data_set,
                       xlsx_file = "data_description",
                       sheetName = "Data Overview",
                       max_levels = 20,
                       max_uniratio = .95,
                       max_na_ratio = 0.50) {
    ## Flag for context recording. If context environment is true, then
    ## the workflow of the data handling will be recorded.
    context_env <- FALSE
    if (exists("context", parent.frame())) {
        context <- get("context", envir = parent.frame())
        if (is.environment(context)) {
            context_env <- TRUE
            exclude_vars <- NULL
        }
    }

    filename <- paste0(xlsx_file, ".xlsx")
    data_desc <- read.xlsx2(filename, sheetName, header = TRUE,
                            stringsAsFactors = FALSE)
    # Target -------------------------------------------------------------------
    objective <-
        data_desc$Variable[data_desc$in_model == "objective"]
    if (length(objective != 1))
        stop("Unique objective variable must be specified.")

    # Artificially excluded ----------------------------------------------------
    exclude_var_1 <- data_desc$Variable[data_desc$in_model == "no"]
    if (context_env & length(exclude_var_1) > 0) {
        exclude_vars <- rbind(
            exclude_vars,
            data.frame(
                vars = exclude_var_1,
                reason = "Artificially excluded",
                stringsAsFactors = FALSE
            )
        )
    }

    # Artifically included -----------------------------------------------------
    include_var_1 <- data_desc$Variable[data_desc$in_model == "yes"]

    # Automatic decision -------------------------------------------------------
    default <- data_desc$Variable[data_desc$in_model == "default"]
    ## Categorical variable: too many levels
    exclude_var_2 <-
        data_desc$Variable[data_desc$Variable %in% default &
                               data_desc$Type == "Character" &
                               as.numeric(data_desc$UniValue) > max_levels]
    default <- default[!default %in% exclude_var_2]
    if (context_env & length(exclude_var_2) > 0) {
        exclude_vars <- rbind(
            exclude_vars,
            data.frame(
                Vars = exclude_var_2,
                reason = "Categorical variable with too many levels",
                stringsAsFactors = FALSE
            )
        )
    }
    ## Missing ratio
    exclude_var_3 <-
        data_desc$Variable[data_desc$Variable %in% default &
                               as.numeric(data_desc$MissingR) > max_na_ratio]
    default <- default[!default %in% exclude_var_3]
    if (context_env & length(exclude_var_3) > 0) {
        exclude_vars <- rbind(
            exclude_vars,
            data.frame(
                Vars = exclude_var_3,
                reason = "Ratio of missing values too high",
                stringsAsFactors = FALSE
            )
        )
    }
    ## HRatio
    exclude_var_4 <-
        data_desc$Variable[data_desc$Variable %in% default &
                               as.numeric(data_desc$HRatio) > max_uniratio]
    default <- default[!default %in% exclude_var_4]
    if (context_env & length(exclude_var_4) > 0) {
        exclude_vars <- rbind(
            exclude_vars,
            data.frame(
                Vars = exclude_var_4,
                reason = "Zero or near zero variance (almost a single value)",
                stringsAsFactors = FALSE
            )
        )
    }

    if (context_env) {
        if (exists("exclude_vars", envir = context)) {
            context$exclude_vars <- rbind(context$exclude_vars, exclude_vars)
        } else {
            context$exclude_vars <- exclude_vars
        }
    }

    ## Final variables in model
    in_model <- c(objective, include_var_1, default)

    # Variable transformation --------------------------------------------------
    data_copy <- lapply(in_model, function(x) {
        y <- data_set[, x]
        type <- data_desc$Type[data_desc$Variable == x]

        if (type == "Charater") {
            if (!is.character(y))
                y <- as.character(y)
        }

        if (type == "Numeric") {
            if (!is.numeric(y))
                y <- as.numeric(as.character(y))
        }

        y
    })
    data_copy <- as.data.frame(data_copy, col.names = in_model,
                               stringsAsFactors = FALSE)
    data_copy
}
